draft: StakeMore Modal Redesign
multisig-labs/app.gogopool.com pull request #461
Opened 2023-09-12 03:14 UTC by swindesr

## Description
**Issue** https://github.com/multisig-labs/app.gogopool.com/issues/443

Updated design for the stake more modal. Many of these pieces end up translating to other new dashboard modals. Posting a draft for now in case Jack wants to see how things are going.

Current steps:

1. get it all working under a new giant component: `NewStakeModal`. using this as a testing grounds for understanding chakra/tailwind/ggp hooks.
2. From there will start to break things out into pieces that make sense and generalize a few of the common new modal treatments.

## Pics
<img width="942" alt="image" src="https://github.com/multisig-labs/app.gogopool.com/assets/22751874/ec2b325d-c9ed-4b38-99d8-b0c8455a586d">

2023-09-18 14:02 UTC, swindesr commented on src/modules/components/Dashboard/Cards/TotalStaked.tsx
> +      {isOpen && <StakeModal onClose={onClose} />}
Moving to the conditional rendering pattern for our modals to prevent calling all of their hooks before actually showing the modal. 

Pros: reduced network calls, faster page interaction
cons: longer load time when you actually open the modal since it needs to now go make the requests

2023-09-18 14:03 UTC, swindesr commented on src/modules/components/Modal/StakeModal/StakeModal.tsx
> +          {hasStake && isLoading && (
Loading/Error screens are not in figma. I tried to replicate another loading screen that Will has mocked in that doc. Waiting on his feedback for design on those.

2023-09-18 14:04 UTC, swindesr commented on src/modules/components/Modal/StakeModal/StakeModal.tsx
> +            {!isSuccess && !isError && (
There is an `Invite and earn GGP` button that appears here when flow is complete, but I don't know what that should do yet so I'm waiting on a Will response.

2023-09-18 14:05 UTC, swindesr commented on src/modules/components/Modal/StakeModal/StakeModalSuccess.tsx
> +      {/* TODO: Insert success graphic and banner */}
Waiting on will response about exporting this graphic as svg. Currently it is ungrouped and not a pleasant export.

2023-09-18 14:06 UTC, swindesr commented on src/modules/components/Modal/StakeModal/StakeModalSuccess.tsx
> +          <Text textColor="yellow.900">COLLATERALIZATION RATIO</Text>
There is a little button shown on the figma mock that I need to figure out the link for before including. Pending Will response.

2023-09-18 20:49 UTC, jacktrusler commented on src/modules/components/Dashboard/Cards/TotalStaked.tsx
> +      {isOpen && <StakeModal onClose={onClose} />}
I like this much better, calling the hooks before modal opening could cause unnecessary errors too.

2023-09-18 20:51 UTC, jacktrusler commented on src/modules/components/Modal/StakeModal/StakeModal.tsx
> +          {hasStake && isLoading && (
I like the mock, gives a good idea at least, easy to swap with another svg.

2023-09-18 20:51 UTC, jacktrusler commented on src/modules/components/Dashboard/Cards/TotalStaked.tsx
> +      {isOpen && <StakeModal onClose={onClose} />}
I like this much better, calling the hooks before modal opening could cause unnecessary errors too.

2023-09-19 14:59 UTC, jacktrusler commented on src/modules/components/Modal/StakeModal/StakeModalForm.tsx
> +    token: ggpAddress as `0x${string}`,
we have a HexString type for this

2023-09-19 15:24 UTC, jacktrusler requested changes
Looks great, some minor changes but mostly LGTM.

2023-09-19 15:24 UTC, jacktrusler commented on src/modules/components/Modal/StakeModal/StakeModalForm.tsx
> +    token: ggpAddress as `0x${string}`,
There's a `HexString` type for this is `cryptoGenerics.ts`

2023-09-19 15:24 UTC, jacktrusler commented on src/modules/components/Modal/StakeModal/StakeModalSuccess.tsx
> +        <Flex py="4">
This needs a drop shadow.

2023-09-19 15:24 UTC, jacktrusler commented on src/modules/components/Modal/StakeModal/StakeModalSuccess.tsx
> +          <Text textColor="yellow.900">COLLATERALIZATION RATIO</Text>
I'm guessing the button is supposed to link to `gogopool.dappling.network/calculator` but we can leave off the button for now. I put a comment on the figma.

2023-09-19 15:24 UTC, jacktrusler commented on src/modules/components/Modal/StakeModal/StakeModalSuccess.tsx
> +        <Flex py="4">
This is fixed

2023-09-20 00:33 UTC, swindesr commented on src/modules/components/Modal/StakeModal/StakeModalSuccess.tsx
> +          <Text textColor="yellow.900">COLLATERALIZATION RATIO</Text>
Cool cool, sounds good. Will update later if needed, but seems safe enough to leave out for now

2023-09-20 00:33 UTC, swindesr commented on src/modules/components/Modal/StakeModal/StakeModalSuccess.tsx
> +        <Flex py="4">
> This is fixed
![image](https://github.com/multisig-labs/app.gogopool.com/assets/22751874/e213e4a9-9efc-4a35-8a82-8dfcf074aff7)

2023-09-25 15:17 UTC, jacktrusler approved these changes

2023-09-25 15:24 UTC, merged